apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  # Nome do recurso ExternalSecret (não é o nome da Secret criada)
  name: kube-prometheus-stack
  # Namespace onde o ExternalSecret e a Secret serão criados
  namespace: monitoring
spec:
  # Intervalo de atualização para sincronizar com o Vault
  refreshInterval: "15s"
  secretStoreRef:
    # Nome do SecretStore que aponta para o Vault
    name: vault-backend
     # Tipo do SecretStore (pode ser ClusterSecretStore também)
    kind: ClusterSecretStore
  target:
    # Nome da Secret do Kubernetes que será criada com os dados do Vault
    name: kube-prometheus-stack
  data:   
    # Nome da chave dentro da Secret do Kubernetes (ex: será montada como um arquivo se usado como volume)
    - secretKey: grafanaAdminUser
      remoteRef:
        # Caminho no Vault (sem o prefixo 'kv/data/') onde está o segredo
        key: infra/kube-prometheus-stack
        # Nome da chave dentro da secret do Vault (ex: se seu JSON estiver salvo no campo 'JSON')
        property: grafanaAdminUser
        
    # Nome da chave dentro da Secret do Kubernetes (ex: será montada como um arquivo se usado como volume)
    - secretKey: grafanaAdminPassword
      remoteRef:
        # Caminho no Vault (sem o prefixo 'kv/data/') onde está o segredo
        key: infra/kube-prometheus-stack
        # Nome da chave dentro da secret do Vault (ex: se seu JSON estiver salvo no campo 'JSON')
        property: grafanaAdminPassword