name: nextcloud
repoURL: https://nextcloud.github.io/helm/
targetRevision: 8.7.0
chart: nextcloud
namespace: nextcloud
values: |
    nextcloud:
        host: drive.oprimoguslab.xyz
        existingSecret:
          enabled: true
          secretName: nextcloud
          usernameKey: username
          passwordKey: password
          tokenKey: ""
          smtpUsernameKey: smtp-username
          smtpPasswordKey: smtp-password
          smtpHostKey: smtp-host
    service:
        port: 80
    ingress:
        enabled: true
        className: traefik
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - drive.oprimoguslab.xyz
            secretName: certs-bundle
    persistence:
        enabled: true
        storageClass: longhorn-retain
        accessMode: ReadWriteOnce
        size: 10Gi
        nextcloudData:
            enabled: true
            storageClass: longhorn-retain
            accessMode: ReadWriteOnce
            size: 200Gi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
        


