name: nextcloud
repoURL: https://nextcloud.github.io/helm/
targetRevision: 8.7.0
chart: nextcloud
namespace: nextcloud
values: |
    nextcloud:
        host: drive.oprimoguslab.xyz
        trustedDomains:
            - drive.oprimoguslab.xyz
    service:
        port: 80
    ingress:
        enabled: true
        className: traefik
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - drive.oprimoguslab.xyz
            secretName: certs-bundle
    persistence:
        enabled: true
        storageClass: longhorn-retain
        accessMode: ReadWriteOnce
        size: 10Gi
        nextcloudData:
            enabled: true
            storageClass: longhorn-retain
            accessMode: ReadWriteOnce
            size: 200Gi
        


