apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-charts
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/oprimogus/oprimoguslab-gitops.git
        revision: main
        files:
          - path: k8s/apps/charts/*.yaml
  template:
    metadata:
      name: '{{name}}'
      namespace: '{{namespace}}'
    spec:
      project: apps
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        chart: '{{chart}}'
        helm:
          values: |
            {{values}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
