apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifests
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/oprimogus/oprimoguslab-gitops.git
        revision: main
        directories:
          - path: k8s/infrastructure/manifests/*
    - list:
        elements:
          - folder: cnpg
            project: databases 
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: '{{path[3]}}'
      source:
        repoURL: https://github.com/oprimogus/oprimoguslab-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
