name: external-secrets-operator
repoURL: https://charts.external-secrets.io
targetRevision: 0.15.1
chart: external-secrets
namespace: external-secrets
values: |
  fullnameOverride: external-secrets-operator
  installCRDs: true
