name: longhorn
repoURL: https://charts.longhorn.io/
targetRevision: 1.10.1
chart: longhorn
namespace: longhorn-system
values: |
  preUpgradeChecker:
    jobEnabled: false
  defaultSettings:
    baseUrl: http://longhorn-backend.longhorn-system.svc.cluster.local:9500
