name: trust-manager
repoURL: https://charts.jetstack.io
targetRevision: 0.20.3
chart: trust-manager
namespace: cert-manager-system
values: |
    namespace: cert-manager-system
    app:
      trust:
        namespace: cert-manager-system
    secretTargets:
      enabled: true
      authorizedSecrets:
        - internal-ca