apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared           # Nome do recurso ExternalSecret (não é o nome da Secret criada)
  namespace: cert-manager                          # Namespace onde o ExternalSecret e a Secret serão criados
spec:
  refreshInterval: "15s"                  # Intervalo de atualização para sincronizar com o Vault
  secretStoreRef:
    name: vault-backend                   # Nome do SecretStore que aponta para o Vault
    kind: ClusterSecretStore                     # Tipo do SecretStore (pode ser ClusterSecretStore também)
  target:
    name: cloudflared         # Nome da Secret do Kubernetes que será criada com os dados do Vault
  data:
    - secretKey: token  # Nome da chave dentro da Secret do Kubernetes (ex: será montada como um arquivo se usado como volume)
      remoteRef:
        key: infra/cloudflared      # Caminho no Vault (sem o prefixo 'kv/data/') onde está o segredo
        property: token                    # Nome da chave dentro da secret do Vault (ex: se seu JSON estiver salvo no campo 'JSON')
    - secretKey: dns-api-token  # Nome da chave dentro da Secret do Kubernetes (ex: será montada como um arquivo se usado como volume)
      remoteRef:
        key: infra/cloudflared      # Caminho no Vault (sem o prefixo 'kv/data/') onde está o segredo
        property: dns-api-token                    # Nome da chave dentro da secret do Vault (ex: se seu JSON estiver salvo no campo 'JSON')    