name: kube-prometheus-stack
repoURL: https://prometheus-community.github.io/helm-charts
targetRevision: 80.6.0
chart: kube-prometheus-stack
namespace: monitoring
values: |
    grafana:
      admin:
        existingSecret: kube-prometheus-stack
        userKey: grafanaAdminUser
        passwordKey: grafanaAdminPassword
      persistence:
        enabled: true
        type: sts
        storageClassName: longhorn-retain
        accessModes:
          - ReadWriteOnce
        size: 20Gi
      ingress:
        enabled: true
        hosts:
          - grafana.oprimoguslab.xyz
      