apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-cluster-client-cert
  namespace: cnpg
spec:
  secretName: postgres-cluster-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
