apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: infrastructure
  annotations:
      # Permite que o segredo seja refletido para outros namespaces
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      # Define quais namespaces podem receber a c√≥pia (* para todos)
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cnpg"
spec:
  secretName: cert-tls
  issuerRef:
    name: letsencrypt-cloudflare-production
    kind: ClusterIssuer
  dnsNames:
  - "oprimoguslab.xyz"
  - "*.oprimoguslab.xyz"
