apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
  namespace: infrastructure
spec:
  secretName: cert-tls
  issuerRef:
    name: letsencrypt-cloudflare-production
    kind: ClusterIssuer
  dnsNames:
  - "oprimoguslab.xyz"
  - "*.oprimoguslab.xyz"
