apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cnpg
spec:
  isCA: true
  commonName: internal-ca
  secretName: internal-ca
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: main-ca-issuer
    kind: ClusterIssuer
